### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by StardustGogeta** [rschwa6308/Physics-2.0#17]
I think that an option to select the background color, possibly using [the standard tkinter window](http://knowpapa.com/cchoser/), would be very nice and require little work to set up.

**Comment by StardustGogeta** [comment]
This has been resolved by commit 6ebdef85387ab2662f6c357c163bd29568f93a5f and can now be closed.

**Comment by rschwa6308** [comment]
Great suggestion!
